---
- name: Ensure UFW allows Shadowsocks
  ufw:
    to_port: "{{ shadowsocks_server_port }}"
    proto: "any"
    rule: "allow"

- name: Ensure UFW allows Shadowsocks
  ufw:
    to_port: "{{ shadowsocks_goquiet_server_port }}"
    proto: "any"
    rule: "allow"
