---
shadowsocks_server_port: "8530"
shadowsocks_goquiet_server_port: "8531"
shadowsocks_local_port: "1080"
shadowsocks_timeout: "600"
shadowsocks_encryption_method: "xchacha20-ietf-poly1305"
shadowsocks_tcp_fast_open: "true"
shadowsocks_obfs_plugin: "obfs-server"
shadowsocks_client_obfs_plugin: "obfs-local"
shadowsocks_obfs_cover_protocol: "tls"
shadowsocks_obfs_cover_domain: "aldana.ddns.net"
shadowsocks_obfs_plugin_opts: "obfs={{ shadowsocks_obfs_cover_protocol }};failover={{ goquiet_webserver }}"
shadowsocks_obfs_client_plugin_opts: "obfs={{ shadowsocks_obfs_cover_protocol }};obfs-host={{ shadowsocks_obfs_cover_domain }}"
shadowsocks_goquiet_plugin: "{{ goquiet_executable }}"
shadowsocks_goquiet_plugin_opts: "{{ goquiet_config }}"
